set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[0]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[1]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[2]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[3]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[4]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[5]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[6]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[7]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[8]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[9]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[10]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[11]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[12]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[13]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[14]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[15]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[16]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[17]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[18]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[19]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[20]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[21]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[22]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[23]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[24]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[25]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[26]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[27]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[28]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[29]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[30]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_prdata[31]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_paddr[0]}]
set_property MARK_DEBUG true [get_nets {U_APB_SLAVE_TOP/APB_M_paddr[1]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[0]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[1]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[2]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[3]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[4]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[5]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[6]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[7]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[8]}]
set_property MARK_DEBUG true [get_nets {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[9]}]
set_property MARK_DEBUG true [get_nets U_APB_SLAVE_TOP/reg00_read_en]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list U_CLK_PROC/fpga_clk_bufg_o]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {U_APB_SLAVE_TOP/APB_M_prdata[0]} {U_APB_SLAVE_TOP/APB_M_prdata[1]} {U_APB_SLAVE_TOP/APB_M_prdata[2]} {U_APB_SLAVE_TOP/APB_M_prdata[3]} {U_APB_SLAVE_TOP/APB_M_prdata[4]} {U_APB_SLAVE_TOP/APB_M_prdata[5]} {U_APB_SLAVE_TOP/APB_M_prdata[6]} {U_APB_SLAVE_TOP/APB_M_prdata[7]} {U_APB_SLAVE_TOP/APB_M_prdata[8]} {U_APB_SLAVE_TOP/APB_M_prdata[9]} {U_APB_SLAVE_TOP/APB_M_prdata[10]} {U_APB_SLAVE_TOP/APB_M_prdata[11]} {U_APB_SLAVE_TOP/APB_M_prdata[12]} {U_APB_SLAVE_TOP/APB_M_prdata[13]} {U_APB_SLAVE_TOP/APB_M_prdata[14]} {U_APB_SLAVE_TOP/APB_M_prdata[15]} {U_APB_SLAVE_TOP/APB_M_prdata[16]} {U_APB_SLAVE_TOP/APB_M_prdata[17]} {U_APB_SLAVE_TOP/APB_M_prdata[18]} {U_APB_SLAVE_TOP/APB_M_prdata[19]} {U_APB_SLAVE_TOP/APB_M_prdata[20]} {U_APB_SLAVE_TOP/APB_M_prdata[21]} {U_APB_SLAVE_TOP/APB_M_prdata[22]} {U_APB_SLAVE_TOP/APB_M_prdata[23]} {U_APB_SLAVE_TOP/APB_M_prdata[24]} {U_APB_SLAVE_TOP/APB_M_prdata[25]} {U_APB_SLAVE_TOP/APB_M_prdata[26]} {U_APB_SLAVE_TOP/APB_M_prdata[27]} {U_APB_SLAVE_TOP/APB_M_prdata[28]} {U_APB_SLAVE_TOP/APB_M_prdata[29]} {U_APB_SLAVE_TOP/APB_M_prdata[30]} {U_APB_SLAVE_TOP/APB_M_prdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {U_APB_SLAVE_TOP/APB_M_paddr[0]} {U_APB_SLAVE_TOP/APB_M_paddr[1]}]]

create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list U_CLK_PROC/U_MMCM_I499M2_O124M8/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 10 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[0]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[1]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[2]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[3]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[4]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[5]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[6]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[7]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[8]} {U_PL_PS_DMA_wrapper/PL_PS_DMA_i/ps8_0_axi_periph_M00_AXI_ARADDR[9]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list U_APB_SLAVE_TOP/reg00_read_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets axi_clk]
